[package]
name    = "dwm1001"
version = "0.1.0"
authors = ["Hanno Braun <hanno@braun-robotics.com>"]


[dependencies]
cortex-m             = { version = "0.5.4", features = [ "const-fn" ] }
cortex-m-rt          = "0.5.2"
cortex-m-semihosting = "0.3.0"
dw1000               = { git = "https://github.com/braun-robotics/rust-dw1000.git" }
embedded-hal         = "0.2.1"
# This is my fork of nrf52-hal. I'm depending on it for the time being, until
# work on it has settled down a bit.
nrf52832-hal         = { git = "https://github.com/braun-robotics/nrf52-hal.git" }

[dev-dependencies]
nb                = "0.1.1"
panic-semihosting = "0.3.0"


[features]
dev         = []                  # expose features of DWM1001-Dev board
rt          = ["nrf52832-hal/rt"]
semihosting = []                  # enable debug output in some examples


[[example]]
name              = "blink"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_id"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_modify"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_rw"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_rx"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_subreg"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_subreg_ext_addr"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_tx"
required-features = ["dev", "rt"]


[profile.release]
codegen-units = 1
lto           = true
opt-level     = 3
