[package]
name    = "dwm1001"
version = "0.1.0"
authors = ["Hanno Braun <hanno@braun-robotics.com>"]


[dependencies]
cortex-m    = "0.5.4"
cortex-m-rt = "0.5.2"
dw1000      = { git = "https://github.com/braun-robotics/rust-dw1000.git" }
# This is my fork of nrf52-hal. I'm depending on it for the time being, until
# work on it has settled down a bit.
nrf52-hal   = { git = "https://github.com/braun-robotics/nrf52-hal.git" }

[dev-dependencies]
cortex-m-semihosting = "0.3.0"
nb                   = "0.1.1"
panic-semihosting    = "0.3.0"


[features]
# Activate this if you're using the DWM1001-Dev board, as opposed to a bare
# DWM1001 module.
dev = []
rt  = ["nrf52-hal/rt"]


[[example]]
name              = "blink"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_id"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_modify"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_rw"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_subreg"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_subreg_ext_addr"
required-features = ["dev", "rt"]


[profile.release]
codegen-units = 1
lto           = true
opt-level     = 3
